Update setup.py
pip-tools seems to require any version of setuptools to work properly (at least on windows10 :s).

```bash
PS D:\Dev\PWSadmin> pip install pip-tools
Collecting pip-tools
  Using cached pip_tools-1.9.0-py2.py3-none-any.whl
Collecting click>=6 (from pip-tools)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting six (from pip-tools)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting first (from pip-tools)
  Using cached first-2.0.1-py2.py3-none-any.whl
Installing collected packages: click, six, first, pip-tools
Successfully installed click-6.7 first-2.0.1 pip-tools-1.9.0 six-1.10.0
PS D:\Dev\PWSadmin> pip-compile.exe .\requirements\requirements.in
Traceback (most recent call last):
  File "c:\python36\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\beebee\.virtualenvs\pws-admin\Scripts\pip-compile.exe\__main__.py", line 5, in <module>
  File "c:\users\beebee\.virtualenvs\pws-admin\lib\site-packages\piptools\scripts\compile.py", line 16, in <module>
    from ..repositories import LocalRequirementsRepository, PyPIRepository
  File "c:\users\beebee\.virtualenvs\pws-admin\lib\site-packages\piptools\repositories\__init__.py", line 3, in <module>
    from .pypi import PyPIRepository
  File "c:\users\beebee\.virtualenvs\pws-admin\lib\site-packages\piptools\repositories\pypi.py", line 17, in <module>
    from ..cache import CACHE_DIR
  File "c:\users\beebee\.virtualenvs\pws-admin\lib\site-packages\piptools\cache.py", line 9, in <module>
    from pkg_resources import Requirement
  File "c:\users\beebee\.virtualenvs\pws-admin\lib\site-packages\pkg_resources\__init__.py", line 70, in <module>
    import packaging.version
ModuleNotFoundError: No module named 'packaging'
```