Control python version used by pre-commit for mypy
Under python versions >= 3.10 mypy will complain about

```
piptools/build.py:120: error: Unused "type: ignore" comment  [unused-ignore]
```

This causes pre-commit.ci to fail, presumably because it uses a recent
version of python.